### ISSUE TITLE
[Feature Request] Mobile support

### ISSUE THREAD

**Issue by TheKrafter** [cassidyjames/clairvoyant#78] opened 2024-02-27 04:09 UTC
It would be nice to use this app on Phones running mobile linux, but currently the app doesnt fill the screen properly, and is cut off in portrait mode:

![App window too small and cut off in portrait mode](https://github.com/cassidyjames/clairvoyant/assets/75903664/2856f5ba-2b9b-45bf-802f-dc2e7ee0893a)

![App window not filling the screen in landscape mode](https://github.com/cassidyjames/clairvoyant/assets/75903664/652615c9-616c-4214-a339-ee99895d8759)

It would be appreciated if when on a mobile device, the app could resize to fill the screen (maybe via an AdwBreakpoint?), and the response text could wrap to fit on the screen.

**Comment by cassidyjames** [comment] 2024-02-27 21:29
Yep, for sure; thanks for reporting! This is actually a duplicate of #38 :)

**Closed by cassidyjames** 2024-02-27 21:29 UTC

**Comment by TheKrafter** [comment] 2024-03-02 04:12
oh! well my bad, I guess I didn't search the issues thoroughly enough

**Comment by cassidyjames** [comment] 2024-03-02 04:35
No worries!
